remote_theme: just-the-docs/just-the-docs  #pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-optional-front-matter
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-readme-index
  - jekyll-relative-links
title: Data 101
description: Data education for kids!
