remote_theme: just-the-docs/just-the-docs
color_schema: blue
plugins:
  - jekyll-remote-theme
  - jekyll-optional-front-matter
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-readme-index
  - jekyll-relative-links
title: Data 101
description: Data education for kids!
